# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: c84b5ec31d9411db7be5b6c0c4dfc8a151511f3a13e9649ad4af684b7b4ca57f71fb63e446d42cb0787c8649756f18fd24f270056ed5d6db0879b653f05d9713

test:
  domain_name: example.com 
  secret_key_base: 580af70c3a704613b64f2f2b3a944370aedbea663634abb28797ac997dc00637e2471428bdd77c973257c2c9b2b2a45ba7834e0da548fad9c5ee182cd02a66ca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
